# Generated by Django 5.0.3 on 2024-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_comment_post_album_photo_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='sharif')),
                ('photo', models.ImageField(upload_to='people')),
                ('professional', models.CharField(max_length=50, verbose_name='kasb')),
            ],
        ),
    ]
